### ISSUE TITLE
/etc/systemd-mutable/user will soon be gone from NixOS

### ISSUE THREAD

**Issue by xaverdh** [svanderburg/dysnomia#6]
Not sure if the path is still used here, but I thought I would drop a notice here: https://github.com/NixOS/nixpkgs/pull/111786/commits/4d2437d7ad18d32a2facd830fb7a454071b3c77e

**Comment by svanderburg** [comment]
It is still used, but changing that path should not be a big problem. The default value is indeed the `systemd-mutable` directory, but the location can be changed with relative ease -- it's just a matter of adjusting the location by providing an additional parameter to the `configure` script.

A couple of days ago, I've noticed that the entire Disnix ecosystem was removed from the Nixpkgs master branch, for a reason that is not valid anymore -- the Dysnomia module was not broken, but there was a security related problem that I probably should have noticed/fixed sooner.

I probably failed to see that issue, because the Nixpkgs issues list is huge and I also get way too much notification email. As a result, it was buried in my backlog for quite some time.

However, I already fixed that particular issue in the Dysnomia module a couple of months ago, several weeks before the 20.09 release (which contains the updated module). Because I did not respond to the Nixpkgs issue, it was removed nonetheless.

I am bit thorn on bringing the Dysnomia module (or the Disnix service) back into Nixpkgs. Disnix, but in particular, the Dysnomia NixOS module implements all kinds of unconventional practices that not all people like. In the Nixpkgs master branch, we typically implement lots of breaking changes that causes difficulties for other people to fix an unconventional module like this.

Maybe I'll still resurrect the packages -- the removed Dysnomia and Disnix NixOS service modules are only needed for multi-user Disnix installations and/or exposing services deployed as part of a NixOS configuration as Dysnomia containers.

Disnix/Dysnomia can still be used in single-user mode or with deployments that do not require already pre-deployed container services.

I still intend to offer these removed NixOS modules separately, that users can still  by adding an import to a NixOS configuration file.

**Comment by svanderburg** [comment]
@xaverdh Ah I checked the proposed change and it seems to be about completely removing the ability to have a mutable systemd directory.

Apart from the fact that Dysnomia relies on such a mutable directory (or rather: the systemd plugin, not the tool itself), I also believe that having such a mutable directory feature at our disposal is still useful, for other reasons than the fact that this tool (and the Nix process management framework) requires it.

Not having an equivalent folder basically means that managing systemd units becomes an all-or-nothing approach. You need to either install a systemd unit in your global Nix profile or the system profile (and these directories are immutable), or you won't be able to deploy any systemd units at all.

I was also sometimes using this "hidden feature" for development purposes. For example, deploying an ad-hoc systemd unit file, for one of my development projects.

Although I consider immutability a good property, being very strict about it and not even offering somebody the option to use it, is something I consider a bad thing. (This btw. has nothing to do with the fact that Dysnomia has a requirement on such a mutable folder).

**Comment by tomberek** [comment]
This issue seems to be stemming from a desire to remove some patching and things perceived as hacks that are specific to Dysnomia. There are some other paths that are searched by default that may be used (https://www.freedesktop.org/software/systemd/man/systemd.unit.html).

I'm not quite sure what the options are here. An alternative folder is probably fine, I doubt there is a set of third-party tools that require Disnix systemd modules to be in the existing location.

Overall, it is very helpful to have a smooth upgrade path. Imperative workflows directly in the pure Nix configurations is often too large of a gap. So we have intermediate methods of using nix-shell, nix-env, profiles, __impure, and so on allow iteration on a solution and debugging. A mutable directory provides this intermediate step for Dysnomia, we should retain it in some form.

If not, is there another way to avoid the "all-or-nothing" aspect of this?

**Comment by deliciouslytyped** [comment]
extra-container uses the directory.
cc @erikarvstedt

**Comment by svanderburg** [comment]
The problem was already fixed with this pull request: https://github.com/NixOS/nixpkgs/pull/116455

I guess this can be closed.

**Comment by svanderburg** [comment]
The Dysnomia module was re-introduced again some time ago and now uses the new configuration property in the above pull request to configure the mutable systemd directory.
